/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

import (
	"encoding/json"
	"strings"
)

type ModelError struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

func (err ModelError) Error() string {
	var w strings.Builder
	json.NewEncoder(&w).Encode(err)
	return w.String()
}

var ErrUserNotFound = ModelError{Code: 404, Message: "User not found"}
var ErrDB = ModelError{Code: 400, Message: "Database error"}
