db:
  user: authservice
  name: authservice
  password: mysql-passwd

auth:
  rootPassword: 'mysql-passwd'
  database: authservice
  username: authservice
  password: 'mysql-passwd'

primary:
  fullname: authservice-mysql
  service:
    type: NodePort
    port: 3306
  persistence:
    enabled: true
    size: 1Gi

secondary:
  replicas: 0

replication:
  enabled: false

volumePermissions:
  enabled: true