apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw02-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw02-app
  template:
    metadata:
      labels:
        app: hw02-app
    spec:
      containers:
      - name: hw02
        image: perevozov/arch:2
        ports:
        - name: web 
          containerPort: 8000
        env:
          - name: HW02_DB_USER
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbUser
          - name: HW02_DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbName
          - name: HW02_DB_HOST
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbHost
          - name: HW02_DB_PASSWD
            valueFrom: 
              secretKeyRef:
                name: hw02-secret
                key: dbPasswd
