# Source: hello-chart/templates/initdb.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "initdb"
spec:
  # POD
  template:
    metadata:
      name: "initdb"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        env:
          - name: MYSQL_PWD
            valueFrom: 
              secretKeyRef:
                name: hw02-secret
                key: dbPasswd
          - name: MYSQL_HOST
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbHost
          - name: HW02_DB_USER
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbUser
          - name: HW02_DB_NAME
            valueFrom: 
              configMapKeyRef:
                name: hw02-config
                key: dbName
    
        image: mysql:latest
        command:
          - sh
          - "-c"
          - |
            mysql -u $HW02_DB_USER $HW02_DB_NAME <<'EOF'
              DROP TABLE user;
              CREATE TABLE IF NOT EXISTS user(
                id int not null auto_increment,
                username varchar(256) not null,
                first_name varchar(256) not null,
                last_name varchar(256) not null,
                email varchar(256),
                phone varchar(256),

                PRIMARY KEY (id)
              );
            EOF

  backoffLimit: 2
