apiVersion: v1
kind: Service
metadata:
  name: emailchecker
  labels: 
    app: emailchecker-app
spec:
  selector:
    app: emailchecker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
