apiVersion: v1
kind: Service
metadata:
  name: userapp
  labels: 
    app: userapp-app
spec:
  selector:
    app: userapp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
