{
 "title": "MyAPP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency (0.5), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (0.95), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (0.99), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, exported_endpoint) (rate(app_request_latency_seconds_bucket[2m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS by endpoint",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(exported_endpoint) (rate(myapp_processed_ops_total[2m]))",
     "legendFormat": "RPS {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS (ingress)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency NGINX (0.5), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency NGINX (0.95), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency NGINX (0.99), ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_response_duration_seconds_bucket[1m]))) * 1000",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  }
 ]
}