apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels: 
    app: authservice-app
spec:
  selector:
    app: authservice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
  type: NodePort
